name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.RuxaMuxa2008 }}" | docker login -u "${{ secrets.nakor1 }}" --password-stdin

    - name: Build Docker image
      run: docker build -t nakor1/animal-farm-nodejs:latest .

    - name: Push Docker image
      run: docker push nakor1/animal-farm-nodejs:latest
